import java.util.zip.ZipFile

plugins {
    application
    alias(libs.plugins.jmh)
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}

repositories { mavenCentral() }

dependencies {
    implementation(project(":"))            // this ExecuTorch engine (brings its native .so via resources)
    implementation(libs.djl.pytorch.engine) // LibTorch baseline (auto-fetches native at runtime)
    implementation(libs.djl.api)            // Image, ImageClassificationTranslator
    runtimeOnly(libs.slf4j.api)
    runtimeOnly(libs.logback.classic)

    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}

application {
    mainClass = "org.measly.example.MobilenetExample"
}

// The README quickstart, runnable. workingDir is the repo root so the default model path
// (native/spike/add.pte) resolves from a fresh clone with no export step.
tasks.register<JavaExec>("runQuickStart") {
    group = "application"
    description = "Runs the README quickstart against native/spike/add.pte."
    mainClass = "org.measly.example.QuickStart"
    classpath = sourceSets["main"].runtimeClasspath
    workingDir = rootProject.projectDir
}

tasks.test { useJUnitPlatform() }

// Model artifacts are generated on demand into this directory (see the exportModels task, Task 3).
val modelsDir = layout.buildDirectory.dir("models")

//val exportModels by tasks.registering(Exec::class) {
val exportModels = tasks.register<Exec>("exportModels") {
    group = "build"
    description = "Generate MobileNetV2 .pte + .pt via uv (heavy; needs uv on PATH)."
    val out = modelsDir.get().asFile
    val script = rootProject.file("tools/scripts/export_mobilenet.py")
    inputs.file(script)
    outputs.files(
        out.resolve("mobilenet_v2.pte"),
        out.resolve("mobilenet_v2_unplanned.pte"),
        out.resolve("mobilenet_v2.pt"),
        out.resolve("versions.json"),
    )
    doFirst { out.mkdirs() }
    workingDir = out
    commandLine("uv", "run", script.absolutePath)
}

// MobileNetV2 lowered to the OpenVINO delegate. Separate from exportModels because the OpenVINO
// AOT path drags in openvino + nncf on top of torch, for a delegate that runs on linux-x86_64
// only -- folding it in would make the default export heavier for everyone who never uses it.
val exportOpenVinoModel = tasks.register<Exec>("exportOpenVinoModel") {
    group = "build"
    description =
        "Generate the OpenVINO-delegated MobileNetV2 .pte via uv (heavy; needs uv on PATH)."
    val out = modelsDir.get().asFile
    val script = rootProject.file("tools/scripts/export_mobilenet_openvino.py")
    inputs.file(script)
    outputs.files(
        out.resolve("mobilenet_v2_openvino.pte"),
        out.resolve("versions_openvino.json"),
    )
    doFirst { out.mkdirs() }
    workingDir = out
    commandLine("uv", "run", script.absolutePath)
}

// W5 output-size sweep models (add_4kb..add_64mb), generated by the same uv pattern.
// Needs flatc on PATH when exporting delegated models — see brief §8 (flatc caveat).
val exportW5Models = tasks.register<Exec>("exportW5Models") {
    group = "build"
    description = "Generate the W5 output-size sweep .pte models via uv (heavy; needs uv on PATH)."
    val out = modelsDir.get().asFile
    val script = rootProject.file("tools/scripts/export_w5_add_models.py")
    inputs.file(script)
    outputs.files(
        out.resolve("add_4kb.pte"),
        out.resolve("add_256kb.pte"),
        out.resolve("add_4mb.pte"),
        out.resolve("add_64mb.pte"),
    )
    doFirst { out.mkdirs() }
    workingDir = out
    commandLine("uv", "run", script.absolutePath)
}

// Pass the models directory to the JVM so ModelArtifacts can resolve it at runtime.
tasks.named<JavaExec>("run") {
    systemProperty("example.models.dir", modelsDir.get().asFile.absolutePath)
}

// The JMH fat jar collides on META-INF/services/ai.djl.engine.EngineProvider: THREE dependencies
// declare one — this project's ExecuTorch provider, djl-api's built-in RPC provider, and
// djl-pytorch-engine's PyTorch provider.
//
// A DuplicatesStrategy picks exactly one and drops the rest, which is wrong for a service file:
// ServiceLoader semantics are a UNION, not a choice. With EXCLUDE the surviving entry was the
// ExecuTorch provider, so the PYTORCH benchmark arm lost its registration and failed at RUNTIME
// with "Deep learning engine not found: PyTorch" — PtEngineProvider.class sitting in the jar the
// whole time, merely unregistered. Nothing fails at build time, which is what let it go unnoticed.
//
// So: drop every copy and add back their union. Computed from the classpath rather than hardcoded,
// so a future engine dependency registers itself instead of silently reintroducing this bug.
val engineProviderService = "META-INF/services/ai.djl.engine.EngineProvider"

val mergeJmhEngineProviders = tasks.register("mergeJmhEngineProviders") {
    description = "Unions every ai.djl.engine.EngineProvider registration for the JMH fat jar."
    // The same sources jmhJar packs: the resolved runtime classpath plus this project's own output.
    val sources = files(
        configurations.named("jmhRuntimeClasspath"),
        sourceSets["main"].output,
        sourceSets["jmh"].output,
    )
    val outDir = layout.buildDirectory.dir("generated/jmh-engine-providers")
    val resource = engineProviderService
    inputs.files(sources).withPropertyName("sources")
    outputs.dir(outDir).withPropertyName("outDir")
    doLast {
        val found = linkedSetOf<String>()
        sources.forEach { f ->
            when {
                f.isDirectory ->
                    File(f, resource).takeIf { it.isFile }?.readLines()?.let { found += it }
                f.isFile && f.name.endsWith(".jar") ->
                    ZipFile(f).use { zip ->
                        zip.getEntry(resource)?.let { entry ->
                            zip.getInputStream(entry).bufferedReader().use { found += it.readLines() }
                        }
                    }
            }
        }
        // Service files allow comments and blank lines; strip them so the merged file is valid.
        val merged = found
            .map { it.substringBefore('#').trim() }
            .filter { it.isNotEmpty() }
        require(merged.isNotEmpty()) {
            "No ai.djl.engine.EngineProvider found on the JMH runtime classpath -- every benchmark " +
                "arm would fail with \"Deep learning engine not found\"."
        }
        // Written under a name that cannot match the exclude pattern below; jmhJar renames it into
        // place. A file already at the service path would be excluded along with the originals.
        val target = outDir.get().file("merged-engine-providers.txt").asFile
        target.parentFile.mkdirs()
        target.writeText(merged.joinToString("\n", postfix = "\n"))
        logger.info("merged {} EngineProvider registration(s): {}", merged.size, merged)
    }
}

tasks.named<Jar>("jmhJar") {
    // Still needed: the fat jar has other legitimate duplicates beyond the service file.
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude(engineProviderService)
    from(mergeJmhEngineProviders) {
        into("META-INF/services")
        rename { "ai.djl.engine.EngineProvider" }
    }
    val expected = listOf(
        "org.measly.executorch.engine.EtEngineProvider",
        "ai.djl.pytorch.engine.PtEngineProvider",
    )
    val jarFile = archiveFile
    val resource = engineProviderService
    doLast { // The failure this fixes is invisible until a benchmark runs, so assert at build time
        val registered = ZipFile(jarFile.get().asFile).use { zip ->
            val entry = requireNotNull(zip.getEntry(resource)) { "jmh jar has no $resource" }
            zip.getInputStream(entry).bufferedReader().use { it.readLines() }
        }
        val missing = expected.filterNot { registered.contains(it) }
        require(missing.isEmpty()) {
            "jmh jar is missing EngineProvider registration(s) $missing; registered=$registered"
        }
    }
}

jmh {
    warmupIterations = 3
    iterations = 5
    fork = 1
    jvmArgs = listOf(
        "-Dexample.models.dir=" + modelsDir.get().asFile.absolutePath,
        // For this specific model, holding interop at 1 is ~11% faster than default on
        // my workstation (i7-1185G7)
        // ExecuTorch is not affected by this setting and in fact all threading settings are
        // set at compilation time
        "-Dai.djl.pytorch.num_interop_threads=1",
    )
}
