# Generated by executorch-runtime-dist release v1.4.1-2. Do not edit by hand.
#
# Select a variant with the helper below; FetchContent only the pair it
# returns, so unused variants download nothing:
#   et_runtime_dist_url("${ET_RUNTIME_VARIANT}" "${platform}" url sha)
#
# The ET_RUNTIME_OPENVINO_* vars are optional: rows exist per platform supplied
# to the release (linux-x86_64, windows-x86_64, plus a windows-x86_64-static alias) and are read
# via et_runtime_openvino_url(<platform> url sha). ET_RUNTIME_OPENVINO_PLATFORM is the DEPRECATED
# legacy var, describing linux-x86_64 only.
# --- Notes for this consumer (djl-executorch-engine) ---
# All three Linux variant rows are committed on purpose: `logging` is the SHIPPED/default runtime;
# `bare` and `devtools` exist ONLY for native/build_variants.sh benchmarking. Shipping only uses logging.
# windows ships `logging` ONLY — there is no bare/devtools Windows build upstream. It ships TWO rows:
# `windows-x86_64` is /MD (dynamic CRT, for CPython extensions) and `windows-x86_64-static` is /MT.
# This engine resolves the -static row so the shipped DLL needs no VC++ redistributable; the /MD row is
# kept because native/tests/cmake_resolution.sh asserts the row is a real choice, not a hardcode.
# All three Linux variant rows are live for linux-x86_64 (default) and linux-aarch64 (arm runners);
# shipping resolves the `logging` row for the host platform.
# The ET_RUNTIME_OPENVINO_* rows are consumed by native/build.sh, which stages a bundle into the
# opt-in OpenVINO jar. It reads the PER-PLATFORM rows and keys them on the platform identity, never
# on the pin row: the windows-x86_64-static row is an ALIAS whose value is a CMake variable
# reference, which shell cannot dereference. The singular ET_RUNTIME_OPENVINO_{PLATFORM,URL,SHA256}
# vars below are deprecated upstream and are deliberately not read here.
# Bump procedure: replace this whole file with the EtRuntimePin.cmake asset from the next
# `v<etver>-<pkgrev>` Repo A release, then re-apply this comment block. The SHA256 change is the
# supply-chain review gate.
set(ET_RUNTIME_VERSION "1.4.1-2")
set(ET_RUNTIME_ET_VERSION "1.4.1")

set(ET_RUNTIME_URL_bare_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-bare-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-aarch64 "30f1ac058915054931af1635e46904fbbd886577314840daebfd1495fbb25795")

set(ET_RUNTIME_URL_devtools_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-devtools-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-aarch64 "2d1e9d96dacf507930b5cf58dc56c228e34c5145b863400397be0925a6ed8404")

set(ET_RUNTIME_URL_logging_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-logging-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-aarch64 "5fe5711300f7b9d0d1a28a6208e8b647ab9faa66aedfd880beb9b59369cbca8a")

set(ET_RUNTIME_URL_bare_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-bare-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-x86_64 "2a38ce044e44fab605502dcfad3ef5e0c5cd153d723515dc2713f17764fb5a37")

set(ET_RUNTIME_URL_devtools_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-devtools-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-x86_64 "cc45ad16043647ba19016117a9a6765f7f509befd091fb907c8b35c662739c69")

set(ET_RUNTIME_URL_logging_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-logging-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-x86_64 "d6fcfb6f03bfe41614cb759363e4058644a8dbc1c1149349881d5040c2019ac6")

set(ET_RUNTIME_URL_logging_windows-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-logging-windows-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64 "4943d68bbf3a0bb9ddb90227a338b815abd2c37e24c5943c5d25797a219ce501")

set(ET_RUNTIME_URL_logging_windows-x86_64-static
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/executorch-runtime-1.4.1-logging-windows-x86_64-static.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64-static "2555bd29f6a6b0f4e7a1fead8f40d5c91af8aac49f1213b503427ce516a97eac")

function(et_runtime_dist_url variant platform out_url out_sha)
  set(_k "${variant}_${platform}")
  if(NOT DEFINED ET_RUNTIME_URL_${_k})
    message(FATAL_ERROR
      "executorch-runtime-dist: no artifact for variant='${variant}' platform='${platform}'")
  endif()
  set(${out_url} "${ET_RUNTIME_URL_${_k}}" PARENT_SCOPE)
  set(${out_sha} "${ET_RUNTIME_SHA256_${_k}}" PARENT_SCOPE)
endfunction()

set(ET_RUNTIME_OPENVINO_VERSION "2025.4.1")
set(ET_RUNTIME_OPENVINO_URL_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/openvino-runtime-2025.4.1-linux-x86_64.tar.gz")
set(ET_RUNTIME_OPENVINO_SHA256_linux-x86_64 "1a147799dcfef408b6f4ba6d526d18bc1f0364fd22c6091cb09a4c14b729e710")

set(ET_RUNTIME_OPENVINO_URL_windows-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/openvino-runtime-2025.4.1-windows-x86_64.tar.gz")
set(ET_RUNTIME_OPENVINO_SHA256_windows-x86_64 "c9e165c9fa5e6aa7456846960eef42b2c5e4543e7afb097f17daaae5bcc39555")

set(ET_RUNTIME_OPENVINO_URL_windows-x86_64-static "${ET_RUNTIME_OPENVINO_URL_windows-x86_64}")
set(ET_RUNTIME_OPENVINO_SHA256_windows-x86_64-static "${ET_RUNTIME_OPENVINO_SHA256_windows-x86_64}")

# Ask for a platform's bundle. Unlike et_runtime_dist_url this does NOT abort when there is no
# row: a platform with no OpenVINO bundle is legitimate (linux-aarch64 has none), so the caller
# gets empty strings and decides. Test the url, do not test DEFINED on a built-up name.
function(et_runtime_openvino_url platform out_url out_sha)
  if(DEFINED ET_RUNTIME_OPENVINO_URL_${platform})
    set(${out_url} "${ET_RUNTIME_OPENVINO_URL_${platform}}" PARENT_SCOPE)
    set(${out_sha} "${ET_RUNTIME_OPENVINO_SHA256_${platform}}" PARENT_SCOPE)
  else()
    set(${out_url} "" PARENT_SCOPE)
    set(${out_sha} "" PARENT_SCOPE)
  endif()
endfunction()

# DEPRECATED: single-bundle variables, kept for consumers written before multi-platform bundles.
# Use et_runtime_openvino_url(<platform> url sha) instead; these describe linux-x86_64 only.
set(ET_RUNTIME_OPENVINO_PLATFORM "linux-x86_64")
set(ET_RUNTIME_OPENVINO_URL
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.4.1-2/openvino-runtime-2025.4.1-linux-x86_64.tar.gz")
set(ET_RUNTIME_OPENVINO_SHA256 "1a147799dcfef408b6f4ba6d526d18bc1f0364fd22c6091cb09a4c14b729e710")

