# Generated by executorch-runtime-dist release v1.3.1-8. Do not edit by hand.
# All three Linux variant rows are committed on purpose: `logging` is the SHIPPED/default runtime;
# `bare` and `devtools` exist ONLY for native/build_variants.sh benchmarking. Shipping only uses logging.
# windows ships `logging` ONLY — there is no bare/devtools Windows build upstream. It ships TWO rows:
# `windows-x86_64` is /MD (dynamic CRT, for CPython extensions) and `windows-x86_64-static` is /MT.
# This engine resolves the -static row so the shipped DLL needs no VC++ redistributable; the /MD row is
# kept because native/tests/cmake_resolution.sh asserts the row is a real choice, not a hardcode.
# The linux-aarch64 rows are currently INERT: no build resolves them yet (see native-build-job.yml).
# Bump procedure: replace this whole file with the EtRuntimePin.cmake asset from the next
# `v<etver>-<pkgrev>` Repo A release, then re-apply this comment block. The SHA256 change is the
# supply-chain review gate.
set(ET_RUNTIME_VERSION "1.3.1-8")
set(ET_RUNTIME_ET_VERSION "1.3.1")

set(ET_RUNTIME_URL_bare_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-bare-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-aarch64 "23f14d418cc8efb9b1268256d92adbed1dfa69fa31f0cbedba048ac8de13bb5d")

set(ET_RUNTIME_URL_devtools_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-devtools-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-aarch64 "6706b0b08bde9583678ae71772ab9477a7e4a6f5b677764c1bd245e63cc898da")

set(ET_RUNTIME_URL_logging_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-logging-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-aarch64 "9a4edf3a9844183db43af9a33d69a95ee2e890c8eb7e753bbb8da6d82408fcbe")

set(ET_RUNTIME_URL_bare_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-bare-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-x86_64 "6af3b0965c88e718a0147346acc12d9212d111118152e5a24607cdb3183fd7ed")

set(ET_RUNTIME_URL_devtools_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-devtools-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-x86_64 "c07bf7590ab339b78c620d182a67444970506548fa7dae196e5df73442f290d9")

set(ET_RUNTIME_URL_logging_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-logging-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-x86_64 "efad8b9709b3c462d9cf049b1459b93cdf4fb9e6d7c73e6356e12aa93cd343f0")

set(ET_RUNTIME_URL_logging_windows-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-logging-windows-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64 "d88c4f29986b7fae58f40c76aaafb0f4d7ce4390b7acc3d0ab5dc460232eae7c")

set(ET_RUNTIME_URL_logging_windows-x86_64-static
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-8/executorch-runtime-1.3.1-logging-windows-x86_64-static.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64-static "c9d929e5f6724dcf03286526e93332acd7d75d7138bb5ade038064992324fa50")

