# Generated by executorch-runtime-dist release v1.3.1-6. Do not edit by hand.
# All three Linux variant rows are committed on purpose: `logging` is the SHIPPED/default runtime;
# `bare` and `devtools` exist ONLY for native/build_variants.sh benchmarking. Shipping only uses logging.
# windows-x86_64 ships `logging` ONLY — there is no bare/devtools Windows build upstream.
# The linux-aarch64 rows are currently INERT: no build resolves them yet (see native-build-job.yml).
# Bump procedure: replace this whole file with the EtRuntimePin.cmake asset from the next
# `v<etver>-<pkgrev>` Repo A release, then re-apply this comment block. The SHA256 change is the
# supply-chain review gate.
set(ET_RUNTIME_VERSION "1.3.1-6")
set(ET_RUNTIME_ET_VERSION "1.3.1")

set(ET_RUNTIME_URL_bare_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-bare-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-aarch64 "4b960120239719aee18bd559028bd994eead92a8e1c454deced0d2f890d0cb3c")

set(ET_RUNTIME_URL_devtools_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-devtools-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-aarch64 "88c979cfa05c9ae3e5bd0bd4e426368e62492d2ca826b68b30fb98827034dd7e")

set(ET_RUNTIME_URL_logging_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-logging-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-aarch64 "feea21ea4d18673601bc7ce231ede25e19a48a1a0ba67d0b02dd490f6ce11eb5")

set(ET_RUNTIME_URL_bare_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-bare-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-x86_64 "bd1aaf0a8000ec3403127d5b61fa4d47df257681956390745fe278b30962d836")

set(ET_RUNTIME_URL_devtools_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-devtools-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-x86_64 "d16b51fc0515fc3bb55e9b9e16014c11e915d39792fa9c15452f7abde124ee98")

set(ET_RUNTIME_URL_logging_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-logging-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-x86_64 "e1c29f4fe7d0e108bfc3a4dc6f0bfb98eb5af97a175b5bae95da61446d8542cd")

set(ET_RUNTIME_URL_logging_windows-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-6/executorch-runtime-1.3.1-logging-windows-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64 "d2bc1859429fe33940adfd110f75d81bb5bedf3163c919d93d8c63531a967a2e")

